[package]
name = "minecraft-bot"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"

[dependencies]
minecraft-protocol = {path="../minecraft-format"}
log = "0.4"
env_logger = "0.9"
array-macro = "2.1"
